#!/usr/bin/env python3
"""
Read parsed Fortran chunks (JSON from parse_fortran.py) and annotate each
with a plain-English 'summary' field generated by Ollama.

Usage:
    python3 parse_fortran.py src/ | python3 summarize_fortran.py
    python3 summarize_fortran.py chunks.json
    python3 summarize_fortran.py --ollama-url http://localhost:11434 chunks.json
"""

import argparse
import json
import sys
import urllib.error
import urllib.request


_DEFAULT_OLLAMA_URL = "http://ollama:11434"
_MODEL = "qwen3-coder-next"


def _build_prompt(chunk: dict) -> str:
    name = chunk["name"]
    kind = chunk["type"]
    source_file = chunk["source_file"]
    line_start = chunk["line_start"]
    line_end = chunk["line_end"]
    calls = chunk.get("calls", [])
    called_by = chunk.get("called_by", [])
    raw_code = chunk["raw_code"]

    return (
        f"You are analyzing a Fortran subroutine from a geodesy codebase.\n"
        f"Subroutine name: {name}\n"
        f"Type: {kind}\n"
        f"File: {source_file}, lines {line_start}-{line_end}\n"
        f"Calls: {calls} (empty list means no calls to other routines)\n"
        f"Called by: {called_by} (pass empty list for now — indexer will populate later)\n"
        f"\n"
        f"Source code:\n"
        f"{raw_code}\n"
        f"\n"
        f"Write a plain-English description of what this subroutine does.\n"
        f"Be specific about: what inputs it takes, what it computes or transforms,\n"
        f"what outputs or side effects it produces. If variable names are opaque,\n"
        f"reason from the operations and call patterns. 3-5 sentences maximum.\n"
        f"Return only the description, no preamble."
    )


def _ollama_generate(base_url: str, prompt: str) -> str:
    url = base_url.rstrip("/") + "/api/generate"
    payload = json.dumps({
        "model": _MODEL,
        "prompt": prompt,
        "stream": False,
    }).encode()

    req = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            body = json.loads(resp.read())
            return body.get("response", "").strip()
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Ollama request failed: {exc}") from exc


def summarize(chunks: list[dict], ollama_url: str) -> list[dict]:
    total = len(chunks)
    results = []
    for i, chunk in enumerate(chunks, start=1):
        name = chunk["name"]
        print(f"Summarizing {i}/{total}: {name}...", file=sys.stderr, flush=True)
        prompt = _build_prompt(chunk)
        summary = _ollama_generate(ollama_url, prompt)
        results.append({**chunk, "summary": summary})
    return results


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Annotate parsed Fortran chunks with Ollama-generated summaries."
    )
    ap.add_argument(
        "input",
        nargs="?",
        help="JSON file from parse_fortran.py (omit to read from stdin)",
    )
    ap.add_argument(
        "--ollama-url",
        default=_DEFAULT_OLLAMA_URL,
        metavar="URL",
        help=f"Ollama base URL (default: {_DEFAULT_OLLAMA_URL})",
    )
    args = ap.parse_args()

    if args.input:
        try:
            with open(args.input) as fh:
                chunks = json.load(fh)
        except OSError as exc:
            print(f"error: cannot read {args.input}: {exc}", file=sys.stderr)
            sys.exit(1)
    else:
        try:
            chunks = json.load(sys.stdin)
        except json.JSONDecodeError as exc:
            print(f"error: invalid JSON on stdin: {exc}", file=sys.stderr)
            sys.exit(1)

    if not isinstance(chunks, list):
        print("error: expected a JSON array of chunks", file=sys.stderr)
        sys.exit(1)

    try:
        annotated = summarize(chunks, args.ollama_url)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    json.dump(annotated, sys.stdout, indent=2)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
